# Generated by Django 5.2.10 on 2026-01-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
