# Generated by Django 5.2.10 on 2026-02-18 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_delete_topic'),
        ('topics', '0002_alter_topic_options_rename_order_topic_order_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('free_text', 'Free Text'), ('latex', 'Latex')], max_length=20)),
                ('prompt', models.TextField()),
                ('choices', models.JSONField(blank=True, null=True)),
                ('answer_key', models.JSONField(blank=True, null=True)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exercises', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exercises', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='topics.topic')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
                'indexes': [models.Index(fields=['course', 'status'], name='courses_exe_course__c27513_idx'), models.Index(fields=['course', 'order_index'], name='courses_exe_course__807ae6_idx'), models.Index(fields=['created_by'], name='courses_exe_created_7913ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'order_index'), name='unique_exercise_order_per_course')],
            },
        ),
    ]
