# Generated by Django 5.2.10 on 2026-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_submission_submissionmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ai_model',
            field=models.CharField(choices=[('claude-sonnet-4-6', 'Claude Sonnet (Anthropic)'), ('gpt-4o', 'GPT-4o (OpenAI)'), ('deepseek-chat', 'DeepSeek Chat')], default='claude-sonnet-4-6', max_length=50),
        ),
    ]
