# Generated by Django 5.2.10 on 2026-01-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order_index', 'created_at']},
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='order',
            new_name='order_index',
        ),
    ]
